apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-prod-projeto-final
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: label-pod-prod-projeto-final
  
      