apiVersion: v1
kind: Pod
metadata:
  name: qa-validadorcpf
  labels:
    app: label-pod-qa-validadorcpf
spec:
  containers:
    - name: pod-qa-java
      image: thiagogaleno/validadorcpf-java
      ports:
        - containerPort: 8081