apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc-pod-dev-projeto-final
spec:
  type: NodePort
  selector:
    app: label-pod-dev-projeto-fina
  ports:
    - port: 8082
      nodePort: 30005 #até 32767