apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-dev-projeto-final
spec:
  template: 
    metadata: 
      name: pod-dev-projeto-final
      labels:
        app: label-pod-dev-projeto-final
    spec: 
      containers:
        - name: container-dev-projeto-final
          image: lucasvscosta/dev-projeto-final
          ports:
            - containerPort: 8082
          env: 
            - name: "DATABASE_URL"
              value: "" 
  replicas: 2
  selector:
    matchLabels:
      app: label-pod-dev-projeto-final 




