apiVersion: apps/v1
kind: Deployment
metadata:
  name: validador-java-dev
spec:
  template: 
    metadata: 
      name: pod-validador-java-dev
      labels:
        app: label-pod-validador-java-dev
    spec: 
      containers:
        - name: container-validador-java-dev
          image: lucasvscosta/validador-cpf-turma-devops:latest
          ports:
            - containerPort: 8082
          env: 
            - name: "DATABASE_URL"
              value: "" 
  replicas: 2
  selector:
    matchLabels:
      app: label-pod-validador-java-dev 




