apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc-pod-validador-java-dev
spec:
  type: NodePort
  selector:
    app: label-pod-validador-java-dev
  ports:
    - port: 8081
      nodePort: 30005 #até 32767